<a href="https://colab.research.google.com/github/Vedika-Hore/python-micro-project/blob/main/Task20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from google.colab import files
uploaded=files.upload()
for fn in uploaded.keys():
  print(fn)

Saving ford_car_dataset.csv to ford_car_dataset (1).csv
ford_car_dataset (1).csv

In [3]:
filepath=("/content/ford_car_dataset (1).csv")
df=pd.read_csv(filepath)
print(df)

         model  year  price transmission  mileage fuelType  tax   mpg  \
0       Fiesta  2017  12000    Automatic    15944   Petrol  150  57.7
1        Focus  2018  14000       Manual     9083   Petrol  150  57.7
2        Focus  2017  13000       Manual    12456   Petrol  150  57.7
3       Fiesta  2019  17500       Manual    10460   Petrol  145  40.3
4       Fiesta  2019  16500    Automatic     1482   Petrol  145  48.7
...        ...   ...    ...          ...      ...      ...  ...   ...
17961    B-MAX  2017   8999       Manual    16700   Petrol  150  47.1
17962    B-MAX  2014   7499       Manual    40700   Petrol   30  57.7
17963    Focus  2015   9999       Manual     7010   Diesel   20  67.3
17964       KA  2018   8299       Manual     5007   Petrol  145  57.7
17965    Focus  2015   8299       Manual     5007   Petrol   22  57.7

       engineSize
0             1.0
1             1.0
2             1.0
3             1.5
4             1.0
...           ...
17961         1.4
17962         1.0
17963         1.6
17964         1.2
17965         1.0

[17966 rows x 9 columns]

In [5]:
print("Independent Feature:")
X = df.drop("price",axis=1)
X

Independent Feature:

         model  year transmission  mileage fuelType  tax   mpg  engineSize
0       Fiesta  2017    Automatic    15944   Petrol  150  57.7         1.0
1        Focus  2018       Manual     9083   Petrol  150  57.7         1.0
2        Focus  2017       Manual    12456   Petrol  150  57.7         1.0
3       Fiesta  2019       Manual    10460   Petrol  145  40.3         1.5
4       Fiesta  2019    Automatic     1482   Petrol  145  48.7         1.0
...        ...   ...          ...      ...      ...  ...   ...         ...
17961    B-MAX  2017       Manual    16700   Petrol  150  47.1         1.4
17962    B-MAX  2014       Manual    40700   Petrol   30  57.7         1.0
17963    Focus  2015       Manual     7010   Diesel   20  67.3         1.6
17964       KA  2018       Manual     5007   Petrol  145  57.7         1.2
17965    Focus  2015       Manual     5007   Petrol   22  57.7         1.0

[17966 rows x 8 columns]

In [6]:
print("Dependent Feature:")
Y=df["price"]
Y

Dependent Feature:

0        12000
1        14000
2        13000
3        17500
4        16500
         ...
17961     8999
17962     7499
17963     9999
17964     8299
17965     8299
Name: price, Length: 17966, dtype: int64

In [8]:
print("Shape of x=",X.shape)
print("Shape of y=",Y.shape)

Shape of x= (17966, 8)
Shape of y= (17966,)

In [19]:
X=df.select_dtypes(include=["int64"])
encoded_df=pd.get_dummies(data=df,dtype=int)
encoded_df.astype(int)
encoded_df.head()

,year,price,mileage,tax,mpg,engineSize,model_ B-MAX,model_ C-MAX,model_ EcoSport,model_ Edge,...,model_ Transit Tourneo,model_Focus,transmission_Automatic,transmission_Manual,transmission_Semi-Auto,fuelType_Diesel,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,2017,12000,15944,150,57.7,1.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,2018,14000,9083,150,57.7,1.0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
2,2017,13000,12456,150,57.7,1.0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
3,2019,17500,10460,145,40.3,1.5,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
4,2019,16500,1482,145,48.7,1.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1

In [25]:
from sklearn.preprocessing import StandardScaler
num_cols=["year","mileage","tax","mpg","engineSize"]
scaler=StandardScaler()
encoded_df[num_cols]=scaler.fit_transform(encoded_df[num_cols])
encoded_df[num_cols].head()

       year   mileage       tax       mpg  engineSize
0  0.065128 -0.380998  0.591358 -0.020442   -0.811386
1  0.552866 -0.733359  0.591358 -0.020442   -0.811386
2  0.065128 -0.560132  0.591358 -0.020442   -0.811386
3  1.040605 -0.662640  0.510727 -1.738890    0.345070
4  1.040605 -1.123724  0.510727 -0.909294   -0.811386

In [41]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(encoded_df,Y,test_size=0.33,random_state=42)

In [37]:
X_train.shape

(12037,)

In [44]:
X_test.shape

(5929, 38)

In [42]:
Y_train.shape

(12037,)

In [43]:
Y_test.shape

(5929,)

In [46]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [49]:
print("Intercept:",model.intercept_)
print("coefficient:",model.coef_)

Intercept: 1.8189894035458565e-12
coefficient: [ 2.75749181e-12  1.00000000e+00  9.11252668e-13 -5.57701752e-13
 -4.15612261e-13 -3.11462965e-13  4.33275753e-14  1.41991856e-13
  3.29516011e-13  1.78218337e-13 -1.36299714e-12 -2.53742604e-13
 -3.41858137e-13  1.26181860e-13  1.84248777e-13  1.43069612e-13
  5.50997490e-14  6.23809560e-14  1.43604576e-14  3.03344720e-13
  1.35858476e-13 -4.33263085e-13 -1.95766655e-14  4.23516474e-22
  1.78980770e-13  1.05879118e-22  5.35308818e-14  4.34796498e-13
  1.78700785e-13 -1.52169808e-13  1.00504536e-13 -2.40763660e-13
  1.40259133e-13  3.83254135e-14  0.00000000e+00  1.71814461e-13
  1.10774156e-13 -3.20913999e-13]

In [51]:
Y_pred = model.predict(X_test)
print("Predicted value:",Y_pred[0:11])
print("Actual value:",Y_test.tolist()[0:11])

Predicted value: [ 6995.  8999.  7998.  5491.  3790. 18200. 22998. 11000.  7600. 14985.
 13995.]
Actual value: [6995, 8999, 7998, 5491, 3790, 18200, 22998, 11000, 7600, 14985, 13995]

In [52]:
from sklearn.metrics import r2_score
r2=r2_score(Y_test,Y_pred)
print("R Square=",r2)

R Square= 1.0

In [ ]:
#The model performs well because the R² score is high, indicating that it explains most of the variation in the target variable.

In [54]:
import joblib

joblib.dump(model,'model.pkl')
joblib.dump(StandardScaler,'scaler.pkl')
joblib.dump(X_train.columns.tolist(),'column.pkl')

['column.pkl']